name: Job1
on:
  workflow_call:
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: dirs/workflow1
    steps:
      - name: Run a one-line script
        run: echo Job1 Executed!
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: test
      - name: Showw status
        run: cat status
